name: geofileopsdev
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.8.1
  - psutil
  - pytest
  - pylint
  - python=3.8
  - pip
  - pydata-sphinx-theme
  - pip:
    - sphinx-automodapi==0.13
    - simplification
