name: geofileopsdev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - geopandas=0.9
  - pygeos
  - psutil
  - pydata-sphinx-theme
  - pip:
    - sphinx-automodapi==0.13
    - simplification
